name: Build and Release Flutter App

on:
  push:
    tags:
      - 'v*.*.*' # Triggers on version tags like v1.0.0
  workflow_dispatch: # Allows manual trigger
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.0.0'

jobs:
  # Build for Android
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '18.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Accept Android SDK licenses
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Create .env file
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env

      - name: Get dependencies
        run: flutter pub get

      - name: Check for lints
        run: flutter analyze

      - name: Build Android APK
        run: flutter build apk --split-per-abi --release

      - name: Upload Android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-builds
          path: build/app/outputs/flutter-apk/*.apk

  # Build for Windows
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Create .env file
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env

      - name: Get dependencies
        run: flutter pub get

      - name: Check for lints
        run: flutter analyze

      - name: Build Windows
        run: flutter build windows --release

      - name: Create Windows ZIP
        run: |
          cd build\windows\x64\runner\Release
          powershell Compress-Archive -Path * -DestinationPath windows-release.zip
          move windows-release.zip ..\..\..\..\

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-builds
          path: build/windows-release.zip

  # Build for Linux
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libblkid-dev liblzma-dev clang cmake pkg-config

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Enable Linux desktop
        run: flutter config --enable-linux-desktop

      - name: Create .env file
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env

      - name: Get dependencies
        run: flutter pub get

      - name: Check for lints
        run: flutter analyze

      - name: Build Linux
        run: flutter build linux --release

      - name: Create Linux tar.gz
        run: |
          cd build/linux/x64/release/bundle
          tar -czf linux-release.tar.gz *
          mv linux-release.tar.gz ../../../../../

      - name: Verify Linux artifact
        run: |
          ls -la build/
          ls -la linux-release.tar.gz

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-builds
          path: linux-release.tar.gz

  # Create Release
  create-release:
    needs: [build-android, build-windows, build-linux]
    runs-on: ubuntu-latest
    if: ${{ always() && needs.build-android.result == 'success' && needs.build-windows.result == 'success' && needs.build-linux.result == 'success' }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version
        id: version
        run: |
          if [[ ${{ github.event_name }} == 'push' ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=v${{ github.event.inputs.version }}
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Display structure of downloaded files
        run: |
          echo "Artifact structure:"
          find ./artifacts -type f -exec ls -la {} \;

      - name: Verify all required files exist
        run: |
          echo "Checking for required files..."
          
          # First, let's see what we actually have
          echo "=== Available artifacts ==="
          find ./artifacts -type f -name "*.apk" -o -name "*.zip" -o -name "*.tar.gz" | sort
          
          echo ""
          echo "=== Detailed artifact structure ==="
          find ./artifacts -type f -exec ls -la {} \;
          
          # Check Android files with more flexible paths
          APK_FILE=$(find ./artifacts -name "*.apk" -type f | head -1)
          
          if [[ -z "$APK_FILE" ]]; then
            echo "ERROR: No Android APK found anywhere in artifacts"
            echo "Android build artifacts:"
            ls -la ./artifacts/android-builds/ 2>/dev/null || echo "No android-builds directory found"
            exit 1
          else
            echo "Found APK(s)."
          fi
          
          # Check Windows files
          ZIP_FILE=$(find ./artifacts -name "*.zip" -type f | head -1)
          if [[ -z "$ZIP_FILE" ]]; then
            echo "ERROR: No Windows ZIP found anywhere in artifacts"
            echo "Windows build artifacts:"
            ls -la ./artifacts/windows-builds/ 2>/dev/null || echo "No windows-builds directory found"
            exit 1
          else
            echo "Found ZIP: $ZIP_FILE"
          fi
          
          # Check Linux files
          TAR_FILE=$(find ./artifacts -name "*.tar.gz" -type f | head -1)
          if [[ -z "$TAR_FILE" ]]; then
            echo "ERROR: No Linux TAR.GZ found anywhere in artifacts"
            echo "Linux build artifacts:"
            ls -la ./artifacts/linux-builds/ 2>/dev/null || echo "No linux-builds directory found"
            exit 1
          else
            echo "Found TAR.GZ: $TAR_FILE"
          fi
          
          echo "All required files found!"

      - name: Rename files for release
        run: |
          mkdir -p ./release-files
          
          # Find asset paths
          ZIP_FILE=$(find ./artifacts -name "*.zip" -type f | head -1)
          TAR_FILE=$(find ./artifacts -name "*.tar.gz" -type f | head -1)
          
          # Copy all Android APKs from the artifact directory to the release directory
          cp ./artifacts/android-builds/*.apk ./release-files/
          
          # Copy and rename other build assets
          cp "$ZIP_FILE" ./release-files/ai_pdf_viewer-${{ steps.version.outputs.version }}-windows.zip
          cp "$TAR_FILE" ./release-files/ai_pdf_viewer-${{ steps.version.outputs.version }}-linux.tar.gz
          
          echo "Files prepared for release:"
          ls -la ./release-files/

      - name: Create Release Notes
        run: |
          cat > RELEASE_NOTES.md << 'EOF'
          # AI PDF Viewer ${{ steps.version.outputs.version }}
          
          ## Downloads
          
          ### Android
          - **APKs**: Multiple APKs are provided for different architectures. Download the one that matches your device (usually `arm64-v8a` for modern phones).
          
          ### Windows
          - **ZIP**: `ai_pdf_viewer-${{ steps.version.outputs.version }}-windows.zip` - Extract and run the executable
          
          ### Linux
          - **TAR.GZ**: `ai_pdf_viewer-${{ steps.version.outputs.version }}-linux.tar.gz` - Extract and run the executable
          
          ## Installation Instructions
          
          ### Android
          1. Download the appropriate APK file for your device
          2. Enable "Install from unknown sources" in your device settings
          3. Install the APK file
          
          ### Windows
          1. Download and extract the ZIP file
          2. Run `ai_pdf_viewer.exe`
          
          ### Linux
          1. Download and extract the tar.gz file
          2. Make the executable file runnable: `chmod +x ai_pdf_viewer`
          3. Run the application: `./ai_pdf_viewer`
          
          ---
          
          Built with ❤️ using Flutter
          EOF

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: AI PDF Viewer ${{ steps.version.outputs.version }}
          body_path: RELEASE_NOTES.md
          files: ./release-files/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}